### ISSUE TITLE
Befragung von Studierenden zur Anforderungsermittlung

### ISSUE THREAD

**Issue by stefanbente** [Archi-Lab/prox-backlog-ipws19#5]
Zur Anforderungsermittlung muss eine Befragung von Studierenden (per Online-Umfrage oder direkter Befragung von Testpersonen) durchgeführt werden. Ziele: 
* Welche Informationen brauchen Studierende über eine/n Professor/in in der Projektbörse?
* Wird von Studierenden der Bedarf gesehen, selbst ein Profil für sich zu verwalten?
* wenn ja, was sollte drinstehen?

**Comment by JohnBryanSpieker** [comment]
Das Team ist der Meinung, dass dieser Punkt abgeschlossen ist.
